# Generated by Django 4.2.7 on 2023-11-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodtruck",
            name="noi_sent",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="foodtruck",
            name="x",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="foodtruck",
            name="y",
            field=models.FloatField(null=True),
        ),
    ]
