# Generated by Django 4.2.7 on 2023-11-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_foodtruckoperatinghour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodtruck",
            name="days_hours",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
